// src/routes/edit/share-options/exports/frameworks/react-chart.ts
const chartTagMap: Record<string, string> = {
	'simple-bar-chart': 'SimpleBarChart',
	'grouped-bar-chart': 'GroupedBarChart',
	'stacked-bar-chart': 'StackedBarChart',
	'line-chart': 'LineChart',
	'area-chart': 'AreaChart',
	'stacked-area-chart': 'StackedAreaChart',
	'scatter-chart': 'ScatterChart',
	'pie-chart': 'PieChart',
	'donut-chart': 'DonutChart'
};

export const createReactChartApp = (chart: any) => {
	const chartData = JSON.stringify(chart.data, null, '\t');
	const chartType = `${chart.type}`;
	let chartOptions = '';
	let theme;
	if (chart && chart.options && chart.options.rawChartOptions) {
		// eslint-disable-next-line prefer-destructuring
		theme = chart.options.rawChartOptions.theme;
		chartOptions = JSON.stringify(chart.options.rawChartOptions, null, '\t');
	}

	let chartTheme = '@carbon/charts/scss';

	const indexHtml = `<div id='root'></div>
`;
	const indexJs
= `import React from 'react';
import ReactDOM from 'react-dom';
import { ${chartTagMap[chartType]} } from '@carbon/charts-react';
import '${chartTheme}';
import { css } from 'emotion';

const app = css\`
	svg.cds--cc--chart-svg {
		height: 500px;
		min-width: 100%
	}
\`;

const options =
	${chartOptions};
class App extends React.Component {
	state = {
	data:
		${chartData}
	};
	render() {
	return (
		<div className={app}>
		<${chartTagMap[chartType]}
			data={this.state.data}
			options={options}>
		</${chartTagMap[chartType]}>
		</div>
	);
	}
}
ReactDOM.render(<App />, document.getElementById('root'));
`;

	const packageJson = {
		dependencies: {
			'@carbon/charts-react': '^1.27.11',
			'@carbon/react': '1.74.0',
			'@carbon/styles': '1.74.0',
			d3: '5.12.0',
			react: '16.12.0',
			'react-dom': '16.12.0',
			'react-scripts': '3.0.1',
			emotion: '10.0.27'
		}
	};

	return {
		'src/index.html': indexHtml,
		'src/index.js': indexJs,
		'package.json': packageJson
	};
};

// src/routes/edit/share-options/exports/frameworks/angular-chart.ts
// Used to map chart types to corresponding angular tag.
const chartTagMap: Record<string, string> = {
	'simple-bar-chart': 'ibm-simple-bar-chart',
	'grouped-bar-chart': 'ibm-grouped-bar-chart',
	'stacked-bar-chart': 'ibm-stacked-bar-Chart',
	'line-chart': 'ibm-line-chart',
	'area-chart': 'ibm-area-chart',
	'stacked-area-chart': 'ibm-stacked-area-chart',
	'scatter-chart': 'ibm-scatter-chart',
	'pie-chart': 'ibm-pie-chart',
	'donut-chart': 'ibm-donut-chart'
};

export const createAngularChartApp = (chart: any) => {
	const chartData = JSON.stringify(chart.data, null, '\t');
	const chartType = `${chart.type}`;
	let chartOptions = '';
	let theme;
	if (chart && chart.options && chart.options.rawChartOptions) {
		// eslint-disable-next-line prefer-destructuring
		theme = chart.options.rawChartOptions.theme;
		chartOptions = JSON.stringify(chart.options.rawChartOptions, null, '\t');
	}

	let chartTheme = '@carbon/charts/scss';

	const appComponentHtml
= `<${chartTagMap[chartType]} [data]='data' [options]='options'></${chartTagMap[chartType]}>
`;
	const appComponentTs
= `import { Component } from '@angular/core';
import '${chartTheme}';
@Component({
	selector: 'app-root',
	templateUrl: './app.component.html'
})
export class AppComponent {
	data = ${chartData};
	options = ${chartOptions};
}
`;
	const appModule
= `import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ChartsModule } from '@carbon/charts-angular';
import { AppComponent } from './app.component';
@NgModule({
	imports: [BrowserModule, ChartsModule],
	declarations: [AppComponent],
	bootstrap: [AppComponent]
})
export class AppModule {}
`;

	const indexHtml
= `<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset='utf-8' />
		<title>Angular</title>
	</head>
	<body>
		<app-root></app-root>
	</body>
</html>
`;

	const mainTs
= `import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
platformBrowserDynamic()
	.bootstrapModule(AppModule)
	.catch(err => console.log(err));
`;

	const angularCliJson
= `{
	"apps": [
		{
			"root": "src",
			"outDir": "dist",
			"assets": ["assets", "favicon.ico"],
			"index": "index.html",
			"main": "main.ts",
			"polyfills": "polyfills.ts",
			"prefix": "app",
			"styles": ["styles.css"],
			"scripts": [],
			"environmentSource": "environments/environment.ts",
			"environments": {
				"dev": "environments/environment.ts",
				"prod": "environments/environment.prod.ts"
			}
		}
	]
}
`;

	const packageJson = {
		dependencies: {
			'@angular/animations': '8.2.14',
			'@angular/common': '8.2.14',
			'@angular/compiler': '8.2.14',
			'@angular/core': '8.2.14',
			'@angular/forms': '8.2.14',
			'@angular/platform-browser': '8.2.14',
			'@angular/platform-browser-dynamic': '8.2.14',
			'@angular/router': '8.2.14',
			'@carbon/charts-angular': '^1.27.11',
			'core-js': '3.6.0',
			d3: '5.15.0',
			rxjs: '6.5.3',
			'zone.js': '0.10.2'
		}
	};

	return {
		'src/index.html': indexHtml,
		'src/main.ts': mainTs,
		'src/app/app.component.html': appComponentHtml,
		'src/app/app.component.ts': appComponentTs,
		'src/app/app.module.ts': appModule,
		'.angular-cli.json': angularCliJson,
		'package.json': packageJson
	};
};
